name: Release datasync content store mongodb
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Installing dependencies
        run: npm install
      - name: Build
        run: npm run build-ts
      - name: Publishing datasync content store mongodb
        id: release-plugin
        uses: JS-DevTools/npm-publish@v2.2.0
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: github-release
        if: steps.release-plugin.outputs.version
        id: github-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:  gh release create v${{ steps.release-plugin.outputs.version }} --title "Release ${{ steps.release-plugin.outputs.version }}" --generate-notes
