name: Release datasync content store mongodb
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Installing dependencies
        run: npm install
      - name: Build
        run: npm run build-ts
      - name: Publishing datasync content store mongodb
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
