name: Release datasync content store mongodb
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Installing dependencies
        run: npm install
      - name: Build
        run: npm run build-ts
      - name: Publishing datasync content store mongodb
        id: release-plugin
        uses: JS-DevTools/npm-publish@v2.2.0
        with:
          token: ${{ secrets.NPM_TOKEN }}
